name: Bad CI/CD pipeline

on: push

jobs:
  build_and_test:  #1. объединили тестирование и сборку
    runs-on: ubuntu-latest  # 2. использовали последнюю версию убунту
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install  # 3. npm install вместо npm ci
      - name: Run Tests
        run: ./run_tests.sh || true  # 4. игнор результата тестов
      - name: Deploy
        # run: ssh user@server "deploy_script.sh"  # 5. небезопасный SSH-доступ
        run: echo "Skipping deploy step for now"
      - name: Build and Deploy
        # run: docker-compose up -d --build  # 6. отсутствие кэширования сборки
        run: echo "Skipping deploy step for now"
