name: Good CI/CD Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Project
        run: docker-compose build  

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: ./run_tests.sh
        continue-on-error: false

  deploy:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: Deploy to Server
        run: ssh -i ~/.ssh/deploy_key user@server "deploy_script.sh"

      - name: Start Application
        run: docker-compose up -d
