name: Good CI/CD Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-20.04  # 1. фиксированная версия убунту
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Dependencies  # 2. кэшируем зависимости
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci  # 3. npm ci вместо npm install для точной установки зависимостей

      - name: Build Project
        run: docker-compose build  

  test:
    runs-on: ubuntu-20.04
    needs: build  # 4. отделили тестирование от сборки
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: ./run_tests.sh  # 5. прерываем выполнение при ошибке в тестах
        continue-on-error: false

  deploy:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: Deploy to Server
        run: ssh -i ~/.ssh/deploy_key user@server "deploy_script.sh"  # 4. настроили безопасный SSH-доступ

      - name: Start Application
        run: docker-compose up -d
